/*
    Mbed OS Target Define Header.
    This contains all of the #defines specific to your target and device.
    It is prepended to every source file using the -include compiler option.
    AUTOGENERATED by "mbed-cmake/configure_for_target.py -a mbed_app.json K64F".  DO NOT EDIT!
    */

#define ARM_MATH_CM4 1
#define COMPONENT_FLASHIAP 1
#define COMPONENT_SD 1
#define CPU_MK64FN1M0VMD12 1
#define DEVICE_ANALOGIN 1
#define DEVICE_ANALOGOUT 1
#define DEVICE_CRC 1
#define DEVICE_EMAC 1
#define DEVICE_FLASH 1
#define DEVICE_I2C 1
#define DEVICE_I2CSLAVE 1
#define DEVICE_INTERRUPTIN 1
#define DEVICE_LPTICKER 1
#define DEVICE_PORTIN 1
#define DEVICE_PORTINOUT 1
#define DEVICE_PORTOUT 1
#define DEVICE_PWMOUT 1
#define DEVICE_RESET_REASON 1
#define DEVICE_RTC 1
#define DEVICE_SERIAL 1
#define DEVICE_SERIAL_ASYNCH 1
#define DEVICE_SERIAL_FC 1
#define DEVICE_SLEEP 1
#define DEVICE_SPI 1
#define DEVICE_SPISLAVE 1
#define DEVICE_SPI_ASYNCH 1
#define DEVICE_STDIO_MESSAGES 1
#define DEVICE_TRNG 1
#define DEVICE_USBDEVICE 1
#define DEVICE_USTICKER 1
#define DEVICE_WATCHDOG 1
#define FEATURE_PSA 1
#define FSL_RTOS_MBED 1
#define MBED_BUILD_TIMESTAMP 1629893862.565823
#define MBED_SPLIT_HEAP 1
#define MBED_TICKLESS 1
#define TARGET_CORTEX 1
#define TARGET_CORTEX_M 1
#define TARGET_FF_ARDUINO 1
#define TARGET_FRDM 1
#define TARGET_Freescale 1
#define TARGET_Freescale_EMAC 1
#define TARGET_K64F 1
#define TARGET_KPSDK_CODE 1
#define TARGET_KPSDK_MCUS 1
#define TARGET_KSDK2_MCUS 1
#define TARGET_LIKE_CORTEX_M4 1
#define TARGET_LIKE_MBED 1
#define TARGET_M4 1
#define TARGET_MBED_PSA_SRV 1
#define TARGET_MCUXpresso_MCUS 1
#define TARGET_MCU_K64F 1
#define TARGET_NAME K64F
#define TARGET_PSA_Target 1
#define TARGET_PSA_V7_M 1
#define TARGET_RELEASE 1
#define TARGET_RTOS_M4_M7 1
#define TOOLCHAIN_GCC 1
#define TOOLCHAIN_GCC_ARM 1
#define __CMSIS_RTOS 1
#define __CORTEX_M4 1
#define __FPU_PRESENT 1
#define __MBED_CMSIS_RTOS_CM 1
#define __MBED__ 1
